version: '3'

services:
  web:
    build: .
    container_name: app
    ports:
      - "1234:5050"
    links:
      - db

  db:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
